# Generated by Django 6.0.2 on 2026-02-13 21:36

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainCategoryMaster',
            fields=[
                ('main_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('main_category_name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=130)),
                ('created_by', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductsGRN_hdr',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('grn_ref_no', models.CharField(max_length=50, unique=True)),
                ('grn_date', models.DateField(default=datetime.datetime.now)),
                ('grn_source', models.CharField(blank=True, max_length=50, null=True)),
                ('delivery_ref_no', models.CharField(blank=True, max_length=50, null=True)),
                ('source_store_id', models.IntegerField(blank=True, null=True)),
                ('grn_store_id', models.IntegerField(blank=True, null=True)),
                ('supplier_id', models.IntegerField(blank=True, null=True)),
                ('supplier_invoice_no', models.CharField(blank=True, null=True)),
                ('purchase_no', models.CharField(blank=True, null=True)),
                ('driver_name', models.CharField(blank=True, null=True)),
                ('driver_contacts', models.CharField(blank=True, null=True)),
                ('vehicle_no', models.CharField(blank=True, null=True)),
                ('seal_no', models.CharField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductMaster',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=120, unique=True)),
                ('description', models.CharField(max_length=130)),
                ('packing_type', models.CharField(blank=True, max_length=50, null=True)),
                ('no_pcs_per_pack', models.IntegerField(blank=True, null=True)),
                ('pcs', models.IntegerField(blank=True, null=True)),
                ('weight_per_pack', models.FloatField(blank=True, null=True)),
                ('weight_per_piece', models.FloatField(blank=True, null=True)),
                ('created_by', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('main_category_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.maincategorymaster')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategoryMaster',
            fields=[
                ('sub_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('sub_category_name', models.CharField(max_length=120, unique=True)),
                ('description', models.CharField(max_length=130)),
                ('created_by', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('main_category_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.maincategorymaster')),
            ],
        ),
        migrations.CreateModel(
            name='ProductsGRN_dtl',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('total_packing', models.IntegerField(blank=True, null=True)),
                ('packing_type', models.CharField(blank=True, max_length=50, null=True)),
                ('no_pcs_per_packing', models.IntegerField(blank=True, null=True)),
                ('total_pcs', models.IntegerField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=200, null=True)),
                ('status_entry', models.CharField(blank=True, max_length=50, null=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, max_length=50, null=True)),
                ('modified_date', models.DateTimeField(auto_now_add=True)),
                ('stock_pcs', models.IntegerField(blank=True, null=True)),
                ('order_no', models.CharField(blank=True, max_length=50, null=True)),
                ('packed_kg', models.FloatField(blank=True, null=True)),
                ('lot_dtl_no', models.CharField(blank=True, max_length=50, null=True)),
                ('bar_code_ref_no', models.CharField(blank=True, max_length=100, null=True)),
                ('rate_per_pcs', models.FloatField(blank=True, null=True)),
                ('total_product_price', models.FloatField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, max_length=20, null=True)),
                ('exchange_rate', models.FloatField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('po_ref_no', models.CharField(blank=True, max_length=50, null=True)),
                ('rack_id', models.CharField(blank=True, max_length=50, null=True)),
                ('alternate_packing_type', models.CharField(blank=True, max_length=50, null=True)),
                ('main_category_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.maincategorymaster')),
                ('product_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productmaster')),
                ('grn_ref_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productsgrn_hdr')),
                ('sub_category_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.subcategorymaster')),
            ],
        ),
        migrations.AddField(
            model_name='productmaster',
            name='sub_category_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.subcategorymaster'),
        ),
    ]
