# Generated by Django 6.0 on 2026-02-06 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainCategoryMaster',
            fields=[
                ('main_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('main_category_name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=130)),
                ('created_by', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategoryMaster',
            fields=[
                ('sub_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('sub_category_name', models.CharField(max_length=120, unique=True)),
                ('description', models.CharField(max_length=130)),
                ('created_by', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('main_category_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.maincategorymaster')),
            ],
        ),
    ]
