# Generated by Django 6.0 on 2026-02-09 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMaster',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=120, unique=True)),
                ('description', models.CharField(max_length=130)),
                ('packing_type', models.CharField(blank=True, max_length=50, null=True)),
                ('no_pcs_per_pack', models.IntegerField(blank=True, null=True)),
                ('pcs', models.IntegerField(blank=True, null=True)),
                ('weight_per_pack', models.FloatField(blank=True, null=True)),
                ('weight_per_piece', models.FloatField(blank=True, null=True)),
                ('created_by', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('main_category_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.maincategorymaster')),
                ('sub_category_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.subcategorymaster')),
            ],
        ),
    ]
