# Generated by Django 6.0 on 2026-02-10 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productsgrn_hdr_productsgrn_dtl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsgrn_dtl',
            name='grn_ref_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productsgrn_hdr'),
        ),
    ]
