# Generated by Django 6.0 on 2026-02-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_productsgrn_hdr_grn_ref_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsgrn_hdr',
            name='grn_ref_no',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
