# Generated by Django 5.2.9 on 2025-12-05 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_departimentmaster_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermaster',
            old_name='paassword',
            new_name='password',
        ),
    ]
