# Generated by Django 5.2.9 on 2025-12-08 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rolemaster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolemaster',
            name='role_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
