# Generated by Django 5.2.9 on 2025-12-10 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_rolemaster_role_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermaster',
            name='department_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.departimentmaster'),
        ),
    ]
