# Generated by Django 5.2.9 on 2025-12-10 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_usermaster_department_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolemaster',
            name='role_status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')], default='ACTIVE', max_length=50),
        ),
        migrations.CreateModel(
            name='UserRoleMapping',
            fields=[
                ('user_role_id', models.AutoField(primary_key=True, serialize=False)),
                ('createdBy', models.CharField(blank=True, max_length=50, null=True)),
                ('updatedBy', models.CharField(blank=True, max_length=100, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('role_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.rolemaster')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.usermaster')),
            ],
        ),
    ]
