# Generated by Django 5.2.9 on 2025-12-10 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rolemaster_role_status_userrolemapping'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserRoleMapping',
            new_name='UserRoleMappingMaster',
        ),
    ]
