# Generated by Django 5.2.9 on 2025-12-12 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_userrolemapping_userrolemappingmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinksMaster',
            fields=[
                ('link_id', models.AutoField(primary_key=True, serialize=False)),
                ('link_name', models.CharField(blank=True, max_length=100, null=True)),
                ('link_url', models.CharField(blank=True, max_length=200, null=True)),
                ('createdBy', models.CharField(blank=True, max_length=50, null=True)),
                ('updatedBy', models.CharField(blank=True, max_length=100, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
