# Generated by Django 5.2.9 on 2025-12-12 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_linksmaster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linksmaster',
            name='link_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='linksmaster',
            name='link_url',
            field=models.CharField(default=1, max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
