# Generated by Django 5.2.9 on 2025-12-12 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_linksmaster_link_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linksmaster',
            name='link_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='linksmaster',
            name='link_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
