# Generated by Django 5.2.9 on 2025-12-12 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_linksmaster_link_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleLinksMappingMaster',
            fields=[
                ('role_link_id', models.AutoField(primary_key=True, serialize=False)),
                ('createdBY', models.CharField(max_length=50, null=True)),
                ('UpdatedBY', models.CharField(max_length=50, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('Link_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.linksmaster')),
                ('role_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.rolemaster')),
            ],
        ),
    ]
