# Generated by Django 5.2.9 on 2025-12-12 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_rolelinksmappingmaster'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rolelinksmappingmaster',
            old_name='Link_id',
            new_name='link_id',
        ),
        migrations.RenameField(
            model_name='rolelinksmappingmaster',
            old_name='UpdatedBY',
            new_name='updatedBY',
        ),
    ]
