# Generated by Django 5.2.9 on 2025-12-12 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_rename_link_id_rolelinksmappingmaster_link_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rolelinksmappingmaster',
            old_name='createdBY',
            new_name='createdBy',
        ),
        migrations.RenameField(
            model_name='rolelinksmappingmaster',
            old_name='updatedBY',
            new_name='updatedBy',
        ),
    ]
