# Generated by Django 5.2.9 on 2025-12-12 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_rename_createdby_rolelinksmappingmaster_createdby_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleDepartimentMappingMaster',
            fields=[
                ('role_departiment_id', models.AutoField(primary_key=True, serialize=False)),
                ('createdBy', models.CharField(max_length=50, null=True)),
                ('updatedBy', models.CharField(max_length=50, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('departiment_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.departimentmaster')),
                ('role_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.rolemaster')),
            ],
        ),
    ]
